### PR TITLE
Add admin entity control methods

### PR DESCRIPTION
**Pull request by almasaeed2010**
@bradfordcondon should the submission get deleted when the rejection is confirmed? Or should we simply filter it out of the results thus keeping a way to "unreject"?

### CODE REVIEW

**Comment by bradfordcondon** [comment]
I originally imagined deleting the data once approved, and keeping the record. However if an admin wanted to un-reject that would be a pain.

Either way i dont think we can delete the request entry.  We'll simply sort  and/or have a seperate table for "past judgement" requests.

**Comment by almasaeed2010** [comment]
I don't think un-rejecting is a pain at least the way we designed it. We just gotta have a filter to make rejected requests show up and the rest will just work.

Rejecting an approved submission should not be possible and instead admin have to delete the entity itself (or unpublish it).

If we agree on that we can merge this branch.

**Comment by bradfordcondon** [comment]
oops yeah i was thinking un-approve.  and yeah, if you unapprove you can delete the entity, but the user has to re-make the submission request. If we were to keep all the serialized data it would be easy to re-apply the request, but i was wondering about storage concerns... probably a non-issue.

I think we can merge.

**Comment by almasaeed2010** [comment]
Alright sounds good to me. Let's keep it simple right now and add the fancy features later :) at least we know it's possible.

I found one issue, I'll fix it and merge.

**Pull request merged**
